cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
      instanceProfile: true
    region:
      auto: true
    fortuneDb:
      password: fortuneDb
      username: fortuneDb
      databaseName: fortuneDb
      readReplicaSupport: false
      