spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
            
cloud:
  aws:
    credentials:
      accessKey: XXX
      secretKey: XXX
      instanceProfile: true
    region:
      auto: true
    rds:
      fortuneDb:
        password: fortuneDb
        username: fortuneDb
        databaseName: fortuneDb
    